[package]
name = "iz"
version = "0.1.0"
authors = ["Alex Fischman <alex@fischman.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
